### ISSUE TITLE
Returned ByteBuffer contains encoded data

### ISSUE THREAD

**Issue by vvviiimmm** [twitter/scrooge#231] opened 2016-03-30 14:05 UTC
Given .thrift file
```thrift
service SimpleService {
    binary foo()
}
```
And implementation:
```scala
class SimpleServiceImpl extends SimpleService[Future] {
    override def foo() = Future[ByteBuffer] {
        ByteBuffer.wrap(Array[Byte](1,2,3))
    }
}
```
Usage:
```scala
val thriftServer = Thrift.serveIface("localhost:2189", new SimpleServiceImpl())
val thriftClient = Thrift.newIface[SimpleService[Future]]("localhost:2189")
val byteBuffer = Await.result(thriftClient.foo())
````
Expected `byteBuffer` to contain `[1,2,3]` but actually it contains 26 values, including name of the function `foo` and wrapped payload `[1,2,3]` at position 22. 
By looking at sources it looks like decoding should be done implicitly using TBinaryProtocol. Should I somehow specify the protocol or should I extract the payload manually?

**Comment by mosesn** [comment] 2016-03-30 15:52
@vvviiimmm smells like a bug.  It should work the way you expect it to.  Does it only behave this way for Binary?  What does it do for String?

**Comment by PapaCharlie** [comment] 2016-09-15 20:58
Sadly, that's not a bug. I just ran into this problem as well. If you look at `byteBuffer`, specifically at its `.position` and `.limit` methods, they'll point to the slice that contains `[1, 2, 3]`. It looks like using the `binary` type can have slightly unexpected behavior. I would recommend using the `.as[Array[Byte]]` conversion from the Bijections package. It handles turning it into the array that you want correctly.

**Comment by mosesn** [comment] 2016-09-15 22:08
Oh, I see.  Yeah, the `ByteBuffer` class needs special care–looking at the underlying array may not give you what you want.  Thanks for updating the ticket @PapaCharlie, I'm going to close it ✨

**Closed by mosesn** 2016-09-15 22:08 UTC
Labels: Starter

**Comment by PapaCharlie** [comment] 2016-09-16 02:22
It does seem a little scary that calling `.array` on a `ByteBuffer` before and after serialization+deserialization returns something different though. A rather easy mistake to make if you aren't familiar with how `ByteBuffer`s work.

**Comment by victordudu1121** [comment] 2018-12-18 12:18
so how fix it then? 
I am experiencing the same problem
@PapaCharlie @mosesn

**Comment by mosesn** [comment] 2018-12-18 15:06
@victordudu1121 don't inspect the contents of the bytebuffer with `ByteBuffer#array`.  Instead use methods like `ByteBuffer.getInt` to read the contents.  Note that ByteBuffer often shares the underlying array with other ByteBuffers to avoid having to copy the contents of an array.

**Comment by PapaCharlie** [comment] 2018-12-18 16:07
The issue is that if the field @victordudu1122 is an array, the API returns a ByteBuffer. The position and limit will be set to the correct slice, but calling to array returns the entite array instead of just the slice. This is just how ByteBuffers are designed. If thrift ever changes the underlying implementation to use direct (off-heap) buffers, then toArray will actually throw a runtime error. The point is, you have to allocate a new byte array of the right size and copy the bytes from the buffer into it
