### ISSUE TITLE
`scroogeGen` list of generated source files is wrong

### ISSUE THREAD

**Issue by stephanh** [twitter/scrooge#188] opened 2015-05-06 02:37 UTC
The list of generated source files that `scroogeGen` in the Scrooge SBT plugin returns contains all the files under `src_managed` instead of just the files added by Scrooge. This means that any existing files are added twice.

Using Scala 2.11 this causes the compiler to fail with the error `x is already defined as ...`.

**Comment by reikje** [comment] 2015-10-22 10:16
I think I am hitting this issue still :( To reproduce:
* clone https://github.com/reikje/scrooge_sbt_2.11_test
* `sbt run`

It works when I:
* either change `scalaVersion` back to  `2.10.x`
* or use `2.11.x` and version `3.14.1` instead of `3.18.1` of the `scrooge-sbt-plugin` under `/project`

**Comment by mosesn** [comment] 2015-10-22 16:51
Hmm, any ideas how to fix this?  I haven't taken a close look yet, any ideas would be helpful.

**Comment by nollbit** [comment] 2016-05-23 06:57
The issue is probably that `ScroogeSBT.newSettings` still remains in both projects having issues [1] [2]. It should have been removed as part of the upgrade (as noted in https://twitter.github.io/scrooge/SBTPlugin.html#migrating-from-3-x-x-to-3-18-0). 

I had a similar issue.

[1] https://github.com/CommBank/uniform/pull/53/files#diff-be2798888ff60368d72f590dd2492755L22
[2] https://github.com/reikje/scrooge_sbt_2.11_test/blob/546819f89f27b3edc1ab30b41eaa82868210d981/build.sbt#L9

**Comment by mosesn** [comment] 2016-05-29 18:17
I think @nollbit's solution is right, so I'm going to marked this as fixed.  Thanks @nollbit!

**Closed by mosesn** 2016-05-29 18:17 UTC
